replicaCount: 1

image:
  repository: docker.io/cube8021/rancher-systems-information
  tag: v0.0.1-rc1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "systems-information"
fullnameOverride: "rancher-systems-information"
namespace: "cattle-system"

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

secretName: "mail-config"
smtp_user: ""
smtp_pass: ""

rancher_name: ""
schedule: "0 0 * * 1"
smtp_host: ""
smtp_port: "587"
to_address: ""
from_address: ""
send_to_support: "true"
