apiVersion: v1
name: kubebackup
version: 0.1.15
appVersion: 0.1.15
description: KubeBackup is a tool for backing up the configuration files in a Kubernetes cluster and uploading them to a S3 bucket.
keywords:
- kubernetes
- backup
home: https://github.com/mattmattox/kubebackup
sources:
- https://github.com/mattmattox/kubebackup
maintainers:
- name: mattmattox
  email: Matthew.Mattox@rancher.com
icon: https://github.com/mattmattox/kubebackup/raw/master/assets/kubebackup-logo.png
