{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "systems-information.Name" . }}
    chart: {{ template "systems-information.chart" . }}
    release: {{ template "systems-information.Name" . }}
  name: {{ template "systems-information.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
